/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;
import Project.ConnectionProvider;
import Project.LoadDB;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.postgresql.util.PSQLException;

/**
 *
 * @author Admin
 */
public class addDiagnosisAndInformation extends javax.swing.JFrame {

    public int flag=0;
    private int pid;
    private String did;
    /**
     * Creates new form addDiagnosisAndInformation
     */
    public addDiagnosisAndInformation(String did) {
        initComponents();
        jLabel2.setVisible(false);
        jLabel7.setVisible(false);
        wardType.setVisible(false);
        this.did = did;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        symptoms = new javax.swing.JTextField();
        diagnosis = new javax.swing.JTextField();
        medicines = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        wardCheck = new javax.swing.JCheckBox();
        wardType = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(80, 150));
        setPreferredSize(new java.awt.Dimension(780, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Patient ID : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 130, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/search.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "Any Major Diseases"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 147, 710, 54));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Patient Id does not exist");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Symptoms : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Diagnosis : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 287, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Medicines : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 340, -1, -1));

        symptoms.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        symptoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symptomsActionPerformed(evt);
            }
        });
        getContentPane().add(symptoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 220, -1));

        diagnosis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(diagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 220, -1));

        medicines.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(medicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 220, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ward Required : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Type of Ward : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        wardCheck.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wardCheck.setText("Yes");
        wardCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardCheckActionPerformed(evt);
            }
        });
        getContentPane().add(wardCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 80, -1));

        wardType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Single", "Duo", " " }));
        wardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardTypeActionPerformed(evt);
            }
        });
        getContentPane().add(wardType, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/save-icon--1.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 398, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/Close.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/add new patient background.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void symptomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symptomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symptomsActionPerformed

    private void wardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wardTypeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new home(this.did).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String patientID=jTextField1.getText();
        try {
            //Connection con=ConnectionProvider.getCon();
            //Statement st=con.createStatement();
            //ResultSet rs=st.executeQuery("select * from patient where patientID='"+patientID+"'");
            // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jLabel2.setVisible(false);
            
            LoadDB db = new LoadDB();
            ResultSet rs = db.getData("select * from patient where pid="+patientID);
            rs.next();
            System.out.println("name:"+rs.getString("name"));
            
            jTable1.getModel().setValueAt(rs.getString("name"), 0, 0);
            jTable1.getModel().setValueAt(rs.getString("age"), 0, 1);
            jTable1.getModel().setValueAt(rs.getString("gen"), 0, 2);
            jTable1.getModel().setValueAt(rs.getString("diseases"), 0, 3);
            
            this.pid = Integer.parseInt(patientID);
            this.flag = 1;
        }
        catch(Exception e)
        {
            jLabel2.setVisible(true);
            JOptionPane.showMessageDialog(null,"Connection Error");
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void wardCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardCheckActionPerformed
        // TODO add your handling code here:
        if(wardCheck.isSelected())
        {
            jLabel7.setVisible(true);
            wardType.setVisible(true);
        }
        else
        {
            jLabel7.setVisible(false);
            wardType.setVisible(false);
        }
    }//GEN-LAST:event_wardCheckActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(this.flag==1)
        {
            
            String symptomsT = symptoms.getText();
            String diagnosisT = diagnosis.getText();
            String medicinesT = medicines.getText();
            String wardReq;
            String typeWard;
            if(wardCheck.isSelected())
            {
                wardReq="YES";
                typeWard=(String)wardType.getSelectedItem();
            }
            else
            {
                wardReq="NO";
                typeWard="";
            }
            
            System.out.println("Data symp :"+symptomsT+"\nward :"+typeWard);
            try {
                //Connection con=ConnectionProvider.getCon();
                //Statement st=con.createStatement();
                //st.executeQuery("insert into patientreport values('"+patientID+"','"+symptoms+"','"++"','"+diagnosis+"','"+medicines+"','"+wardReq+"','"+typeWard+"')");
                int n=0;
                LoadDB db = new LoadDB();
                
                //Adding exception if primary key is voilated
                ResultSet rs = db.getData("select * from  \"Diagnosis\" where pid="
                        +this.pid+" and did='"+this.did+"'");
                if(rs.next()){
                    
                    System.out.println("already exists 1");
                    
                }else{
                    n = db.update("insert into \"Diagnosis\" values("+this.pid+",'"+
                    this.did+"','"+symptomsT+"','"+diagnosisT+"','"+
                    medicinesT+"','"+typeWard+"')");
                }
                
                if(n>0){
                    JOptionPane.showMessageDialog(null,"Succesfully Updated");
                    setVisible(false);
                    new addDiagnosisAndInformation("d001").setVisible(true);
                }else{
                    System.out.println("already exists");
                }
                        
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else
            JOptionPane.showMessageDialog(null,"Patient field is empty");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDiagnosisAndInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDiagnosisAndInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDiagnosisAndInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDiagnosisAndInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDiagnosisAndInformation("d001").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diagnosis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField medicines;
    private javax.swing.JTextField symptoms;
    private javax.swing.JCheckBox wardCheck;
    private javax.swing.JComboBox<String> wardType;
    // End of variables declaration//GEN-END:variables
}
